### ISSUE TITLE
Unable to read directory entries (Python)

### ISSUE THREAD

**Issue by benmezger** [vog/texcaller#5]
I am unable to convert a tex file to a pdf. I keep getting `Unable to read directory entries`. I am injecting variables to my tex file using Jinja's templating system, however,  after getting the correct result, I try to convert the new tex file to a pdf. Here a snippet;

```python
    env = Environment(loader=FileSystemLoader('templates'))
    dynamic_page = env.get_template('dynamic.tex')

    dynamic_vals = {
        "title": "rice",
        "spon": "beans",
    }
    output_from_parsed_template = dynamic_page.render(**dynamic_vals)
    pdf, info = texcaller.convert(output_from_parsed_template, 'LaTeX', 'PDF', 5)

    print('PDF size: %.1f KB' % (len(pdf) / 1024.0))
```

Which gives me:

```python
Traceback (most recent call last):
  File "generator.py", line 49, in <module>
    pdf, info = texcaller.convert(output_from_parsed_template, 'LaTeX', 'PDF', 5)
  File "/Users/seds/.virtualenvs/texpdf/lib/python2.7/site-packages/texcaller-0-py2.7-macosx-10.13-x86_64.egg/texcaller.py", line 171, in convert
    val = _texcaller.convert(source, source_format, result_format, max_runs)
ValueError: Unable to read directory entries of "/var/folders/zc/0ynmz43s3tqgh9m30m0s3h0w0000gn/T//texcaller-temp-kV13BA": No such file or directory.
```

Any idea how this could be fixed?

```shell
Darwin SEDSs-MacBook-Pro.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
```
High Sierra 10.13.2 (17C88)

**Comment by vog** [comment]
Your code looks fine to me.

It seems there is some issue with handling the temporary folder. Texcaller creates and manages a temporary folder in which it runs LaTeX, so it able to safely remove any intermediate files created by LaTeX.

The location of the temporary directory looks strange to me. The last part "texcaller-temp-kV13BA" is from Texcaller, the first part is from your system. Usually I'd expect it to be something like "/tmp/texcaller-temp-kV13BA" or "/var/tmp/texcaller-temp-kV13BA". Maybe you could try to set the TMP environment variable to an existing directory and see what happens.

**Comment by benmezger** [comment]
> Usually I'd expect it to be something like "/tmp/texcaller-temp-kV13BA" or "/var/tmp/texcaller-temp-kV13BA".

Yes, this is what I thought at first, however, it seems that my shell is setting `TMPDIR` to `/var/folders/zc/0ynmz43s3tqgh9m30m0s3h0w0000gn/T/`. I tried changing the `TMPDIR` variable to `/tmp/`, but I get the same error.

```
Traceback (most recent call last):
  File "generator.py", line 49, in <module>
    pdf, info = texcaller.convert(output_from_parsed_template, 'LaTeX', 'PDF', 5)
  File "/Users/seds/.virtualenvs/texpdf/lib/python2.7/site-packages/texcaller-0-py2.7-macosx-10.13-x86_64.egg/texcaller.py", line 171, in convert
    val = _texcaller.convert(source, source_format, result_format, max_runs)
ValueError: Unable to read directory entries of "/tmp/texcaller-temp-Oa3nST": No such file or directory.
```

It seems this error is coming from [here](https://github.com/vog/texcaller/blob/master/c/texcaller.c#L127).  Any workaround?

**Comment by benmezger** [comment]
Ok, I have solved the issue. It seems that `pdflatex` was not found in my path, which gave me that error. Setting the correct path solved my issue (`export PATH="$PATH:/Library/TeX/texbin"`).
In either case, the error is a bit odd too. Would be nice to first check the if the command exists.

Regards

**Comment by vog** [comment]
> Would be nice to first check the if the command exists.

You are right, this specific type of error is not handled correctly.

**Comment by vog** [comment]
@benmezger Would you mind checking the latest master?

Instead of the misleading error message, you should now get something like this:

> Command "pdflatex" terminated with exit status 1.

**Comment by benmezger** [comment]
@vog works like a charm. Thanks for the library!

**Comment by vog** [comment]
@benmezger Thanks for verifying the fix.
