### ISSUE TITLE
source = source.encode('UTF-8') UnboundLocalError: local variable 'source' referenced before assignment

### ISSUE THREAD

**Issue by sahilm89** [vog/texcaller#7]
I am trying to import convert from texcaller to convert a piece of latex code to pdf. Here's the error message:

```
  File "printStoichMatrix.py", line 36, in latexToPDF
    pdf, info = convert(latex,'LaTeX', 'PDF', 5)
  File "/usr/local/lib/python2.7/dist-packages/texcaller-0-py2.7-linux-x86_64.egg/texcaller.py", line 104, in convert
    source = source.encode('UTF-8')
```

**Comment by vog** [comment]
Which SWIG version do you use? What is the output of the following command?

    swig -version

**Comment by sahilm89** [comment]
```
swig -version

SWIG Version 2.0.12

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre
```

**Comment by vog** [comment]
Please use SWIG 3.0, or use an older texcaller version that used SWIG 2.0. There were some incompatible changes from SWIG 2.0 to SWIG 3.0 to which texcaller was adapted.

**Comment by vog** [comment]
Since I didn't get a response from you for over 2 years, I assume that using SWIG 3.0 solved your problem. If not, feel free to open another issue.
