### ISSUE TITLE
Is there are possible way to use this on windows

### ISSUE THREAD

**Issue by Sups4** [vog/texcaller#8]
Im Programming with Visual Studio on win64, it seems like its not possible for me to use ur files :/

**Comment by vog** [comment]
This library is not meant to be compiled on Windows. Among others, it uses the `fork()` and `execlp()` system calls which are present on every Unix-like operating system, but not on Windows.

Nevertheless, feel free to provide a portability patch as pull request, if you like. Except for those specific parts, the rest of the library is standard, portable C code. There shouldn't be any obstacles except for the mentioned system calls.
